
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/aws_oauth2_test_website;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        proxy_buffer_size 16k;
        proxy_buffers 4 16k;
        proxy_busy_buffers_size 16k;
        large_client_header_buffers 4 16k;

        location = /oauth2/auth {
            internal;
            proxy_pass http://127.0.0.1:4180;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
        }

        location = /oauth2/auth-admin {
            internal;
            proxy_pass http://127.0.0.1:4180/oauth2/auth?allowed_groups=site-admins;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
        }

        location = /oauth2/auth-editor {
            internal;
            proxy_pass http://127.0.0.1:4180/oauth2/auth?allowed_groups=site-editors,site-admins;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
        }

        location /oauth2/ {
            proxy_pass http://127.0.0.1:4180;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

		location /realms/ {
    		proxy_pass http://127.0.0.1:8080;
    		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-Proto $scheme;
		}

        location /admin/ {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        }

        location /resources/ {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        }

        location / {
            auth_request /oauth2/auth;
            error_page 401 = /oauth2/sign_in;
            root /var/www/aws_oauth2_test_website;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location = /nginx-status {
            auth_request /oauth2/auth-admin;
            error_page 401 = /oauth2/sign_in;
            stub_status;
        }

        location = /index5.html {
            auth_request /oauth2/auth-editor;
            error_page 401 = /oauth2/sign_in;
            root /var/www/aws_oauth2_test_website;
        }
